analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.33305
title: Transference
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.9845623
  brandStrength: 0.375
  rhythmicContrast: 0.25
  brandColors:
    - '#040505'
    - '#223b3a'
    - '#494f4d'
    - '#6f645a'
    - '#8e8980'
  lightness: 0.05196574
purpose: []
favicon: null
name: Transference
typography_spectrum: 0.74374
