layout_spectrum: 1
typography_spectrum: 1
color:
  saturation: 0.9845623
  lightness: 0.05196574
  brandStrength: 1
  brandColors:
    - '#010202'
    - '#5C7888'
    - '#4B4342'
    - '#ABC7C6'
    - '#F8FBE7'
  rhythmicContrast: 0.5622655
name: Transference
