title: Transference
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1045531
  brandStrength: 0
  lightness: 0.05196574
  brandColors:
    - '#040505'
    - '#223b3a'
    - '#494f4d'
    - '#6f645a'
    - '#8e8980'
  rhythmicContrast: 0.2892074
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Transference
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.74374
layout_spectrum: 0
