name: Transference
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74374
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040505'
    - '#223b3a'
    - '#494f4d'
    - '#6f645a'
    - '#8e8980'
  brandStrength: 0.375
  lightness: 0.05196574
  saturation: 0.9845623
  rhythmicContrast: 0.5
purpose: []
